### PR TITLE
Adding deforming-objects-workflows

### PR DESCRIPTION
**Pull request by LB-JakubSkorupka**
Signed-off-by: LB-JakubSkorupka <86951967+LB-JakubSkorupka@users.noreply.github.com>

**Change Summary**

Adding Deforming Objects Workflows and screenshots for that document in "images" folder.

### CODE REVIEW

**Comment by lgleim** [comment]
@hultonha @amzn-rhhong Could you potentially have a look at this PR?

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS to take a look too, thanks!

**Review by hultonha — APPROVED** [review]
Changes look good to me! Thanks for adding them @LB-JakubSkorupka 👍

**Review by FuzzyCarterAWS — APPROVED** [review]
This looks great. One small change proposed that I'll accept the changes for.

**Pull request merged**
