### PR TITLE
Minor change to workflow doc based on feedback

### PR DESCRIPTION
**Pull request by michleza**
According to lionbridge feedback the NVcloth gem is also required to complete some of these areas. Updating the doc to include it as a requirement.

### CODE REVIEW

**Comment by moraaar** [comment]
> According to lionbridge feedback the NVcloth gem is also required to complete some of these areas. Updating the doc to include it as a requirement.

Please ask Lionbridge to provide more information, because there is no relation between ragdolls and cloth. All ragdolls workflow can be done without having `NVIDIA Cloth` gem enabled.

**Comment by lgleim** [comment]
@michleza Were you able to verify the requirement with Lionbridge?

**Comment by adamdbrw** [comment]
@michleza could you please comment on the feedback?

**Comment by adamdbrw** [comment]
@michleza if you could respond by 10.09.2023, it would be great. Otherwise we will close this issue.

**Pull request closed without merging**
